global:
  scrape_interval: 30s

remote_write:
  - url: https://prometheus-prod-55-prod-gb-south-1.grafana.net/api/prom/push
    basic_auth:
      username: *******
      password: ****************************************************************************************************************

scrape_configs:
  - job_name: 'discord-bot'
    static_configs:
      - targets: ["discord-bot:9091"]